language: node_js
node_js:
  - "6.14.1"

sudo: false

script:
  - "npm install"

after_success:
  - bash <(curl -s https://scripts.scantist.com/staging/ci-travis-jar.sh)
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
